openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /sessioninfo:
    get:
      summary: Secure Api
      operationId: secure_api_sessioninfo_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /blocks:
    post:
      tags:
      - threads
      summary: Create
      operationId: create_blocks_post
      parameters:
      - name: thread_title
        in: query
        required: true
        schema:
          type: string
          title: Thread Title
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBlockModel'
      responses:
        '200':
          description: Create a new block
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    get:
      tags:
      - threads
      summary: Get Blocks By Date
      operationId: get_blocks_by_date_blocks_get
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Date'
      responses:
        '200':
          description: Get all blocks for a given date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockCollection'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /journal:
    get:
      tags:
      - threads
      summary: Get Journal By Date
      operationId: get_journal_by_date_journal_get
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Date'
        required: true
      responses:
        '200':
          description: Get journal for a given date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockCollection'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /threads:
    get:
      tags:
      - threads
      summary: Get All Threads
      operationId: get_all_threads_threads_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ThreadsModel'
                type: array
                title: Response Get All Threads Threads Get
    post:
      tags:
      - threads
      summary: Create Thread
      operationId: create_thread_threads_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateThreadModel'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /threads/{title}:
    put:
      tags:
      - threads
      summary: Update Thread
      operationId: update_thread_threads__title__put
      parameters:
      - name: title
        in: path
        required: true
        schema:
          type: string
          title: Title
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateThreadModel'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    get:
      tags:
      - threads
      summary: Get Thread
      operationId: get_thread_threads__title__get
      parameters:
      - name: title
        in: path
        required: true
        schema:
          type: string
          title: Title
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    BlockCollection:
      properties:
        blocks:
          items:
            $ref: '#/components/schemas/BlockModel'
          type: array
          title: Blocks
      type: object
      required:
      - blocks
      title: BlockCollection
      example:
        blocks:
        - content: This is the content of the block
        - content: This is the content of the block
    BlockModel:
      properties:
        _id:
          type: string
          format: uuid
          title: ' Id'
        content:
          type: string
          title: Content
        created_at:
          type: string
          format: date-time
          title: Created At
      type: object
      required:
      - content
      title: BlockModel
      example:
        content: This is the content of the block
        created_at: '2021-01-01T00:00:00.000000'
        id: 12345678-1234-5678-1234-567812345678
    CreateThreadModel:
      properties:
        type:
          type: string
          title: Type
        title:
          type: string
          maxLength: 100
          minLength: 1
          pattern: ^[a-zA-Z0-9]+$
          title: Title
        content:
          items:
            $ref: '#/components/schemas/BlockModel'
          type: array
          title: Content
      type: object
      required:
      - type
      - title
      title: CreateThreadModel
      example:
        content:
        - content: This is the content of the block
        - content: This is the content of the block
        title: This is the title of the thread
        type: /new-plan
    Date:
      properties:
        date:
          type: string
          format: date-time
          title: Date
      type: object
      required:
      - date
      title: Date
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ThreadModel:
      properties:
        _id:
          type: string
          format: uuid
          title: ' Id'
        creator:
          type: string
          title: Creator
        created_date:
          type: string
          format: date-time
          title: Created Date
        type:
          type: string
          title: Type
        title:
          type: string
          maxLength: 100
          minLength: 1
          pattern: ^[a-zA-Z0-9]+$
          title: Title
        content:
          items:
            $ref: '#/components/schemas/BlockModel'
          type: array
          title: Content
      type: object
      required:
      - creator
      - type
      - title
      title: ThreadModel
      example:
        content:
        - content: This is the content of the block
        - content: This is the content of the block
        created_date: '2021-01-01T00:00:00.000000'
        creator: user1
        title: This is the title of the thread
        type: /new-plan
    ThreadsModel:
      properties:
        threads:
          items:
            $ref: '#/components/schemas/ThreadModel'
          type: array
          title: Threads
      type: object
      required:
      - threads
      title: ThreadsModel
      example:
        threads:
        - content:
          - content: This is the content of the block
          - content: This is the content of the block
          created_date: '2021-01-01T00:00:00.000000'
          creator: user1
          title: This is the title of the thread
          type: /new-plan
        - content:
          - content: This is the content of the block
          - content: This is the content of the block
          created_date: '2021-01-01T00:00:00.000000'
          creator: user1
          title: This is the title of the thread
          type: /new-plan
    UpdateBlockModel:
      properties:
        content:
          type: string
          title: Content
      type: object
      title: UpdateBlockModel
      example:
        content: This is the content of the block
    UpdateThreadModel:
      properties:
        content:
          items:
            $ref: '#/components/schemas/BlockModel'
          type: array
          title: Content
      type: object
      required:
      - content
      title: UpdateThreadModel
      example:
        content:
        - content: This is the content of the block
        - content: This is the content of the block
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
