components:
  schemas:
    BlockCollection:
      example:
        blocks:
        - content: This is the content of the block
        - content: This is the content of the block
      properties:
        blocks:
          items:
            $ref: '#/components/schemas/BlockModel'
          title: Blocks
          type: array
      required:
      - blocks
      title: BlockCollection
      type: object
    BlockModel:
      example:
        content: This is the content of the block
        created_at: '2021-01-01T00:00:00.000000'
        id: 12345678-1234-5678-1234-567812345678
      properties:
        _id:
          format: uuid
          title: ' Id'
          type: string
        content:
          title: Content
          type: string
        created_at:
          format: date-time
          title: Created At
          type: string
      required:
      - content
      title: BlockModel
      type: object
    CreateThreadModel:
      example:
        content:
        - content: This is the content of the block
        - content: This is the content of the block
        title: This is the title of the thread
        type: /new-plan
      properties:
        content:
          items:
            $ref: '#/components/schemas/BlockModel'
          title: Content
          type: array
        title:
          maxLength: 100
          minLength: 1
          pattern: ^[a-zA-Z0-9]+$
          title: Title
          type: string
        type:
          title: Type
          type: string
      required:
      - type
      - title
      title: CreateThreadModel
      type: object
    Date:
      properties:
        date:
          format: date-time
          title: Date
          type: string
      required:
      - date
      title: Date
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ThreadModel:
      example:
        content:
        - content: This is the content of the block
        - content: This is the content of the block
        created_date: '2021-01-01T00:00:00.000000'
        creator: user1
        title: This is the title of the thread
        type: /new-plan
      properties:
        _id:
          format: uuid
          title: ' Id'
          type: string
        content:
          items:
            $ref: '#/components/schemas/BlockModel'
          title: Content
          type: array
        created_date:
          format: date-time
          title: Created Date
          type: string
        creator:
          title: Creator
          type: string
        title:
          maxLength: 100
          minLength: 1
          pattern: ^[a-zA-Z0-9]+$
          title: Title
          type: string
        type:
          title: Type
          type: string
      required:
      - creator
      - type
      - title
      title: ThreadModel
      type: object
    ThreadsModel:
      example:
        threads:
        - content:
          - content: This is the content of the block
          - content: This is the content of the block
          created_date: '2021-01-01T00:00:00.000000'
          creator: user1
          title: This is the title of the thread
          type: /new-plan
        - content:
          - content: This is the content of the block
          - content: This is the content of the block
          created_date: '2021-01-01T00:00:00.000000'
          creator: user1
          title: This is the title of the thread
          type: /new-plan
      properties:
        threads:
          items:
            $ref: '#/components/schemas/ThreadModel'
          title: Threads
          type: array
      required:
      - threads
      title: ThreadsModel
      type: object
    TitleModel:
      example:
        titles:
        - TitleThis
        - TitleThat
      properties:
        titles:
          items:
            type: string
          title: Titles
          type: array
      required:
      - titles
      title: TitleModel
      type: object
    UpdateBlockModel:
      example:
        content: This is the content of the block
      properties:
        content:
          title: Content
          type: string
      title: UpdateBlockModel
      type: object
    UpdateThreadModel:
      example:
        content:
        - content: This is the content of the block
        - content: This is the content of the block
      properties:
        content:
          items:
            $ref: '#/components/schemas/BlockModel'
          title: Content
          type: array
      required:
      - content
      title: UpdateThreadModel
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /blocks:
    get:
      operationId: get_blocks_by_date_blocks_get
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Date'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockCollection'
          description: Get all blocks for a given date
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Blocks By Date
      tags:
      - threads
    post:
      operationId: create_blocks_post
      parameters:
      - in: query
        name: thread_title
        required: true
        schema:
          title: Thread Title
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBlockModel'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadModel'
          description: Create a new block
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create
      tags:
      - threads
  /journal:
    get:
      operationId: get_journal_by_date_journal_get
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Date'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockCollection'
          description: Get journal for a given date
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Journal By Date
      tags:
      - threads
  /sessioninfo:
    get:
      operationId: secure_api_sessioninfo_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Secure Api
  /threads:
    get:
      operationId: get_all_threads_threads_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ThreadsModel'
                title: Response Get All Threads Threads Get
                type: array
          description: Successful Response
      summary: Get All Threads
      tags:
      - threads
    post:
      operationId: create_thread_threads_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateThreadModel'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadModel'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create Thread
      tags:
      - threads
  /threads/{title}:
    get:
      operationId: get_thread_threads__title__get
      parameters:
      - in: path
        name: title
        required: true
        schema:
          title: Title
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadModel'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Thread
      tags:
      - threads
    put:
      operationId: update_thread_threads__title__put
      parameters:
      - in: path
        name: title
        required: true
        schema:
          title: Title
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateThreadModel'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadModel'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Update Thread
      tags:
      - threads
  /titles:
    get:
      operationId: thread_titles_titles_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TitleModel'
          description: Get all thread titles
      summary: Thread Titles
      tags:
      - threads
