version: '3.8'

services:
  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    environment:
      - BASE_URL=${BASE_URL}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
      - INSTALL_DOMAIN=${INSTALL_DOMAIN}
      - HCP_CLIENT_ID=${HCP_CLIENT_ID}
      - HCP_CLIENT_SECRET=${HCP_CLIENT_SECRET}
      - HCP_ORG_ID=${HCP_ORG_ID}
      - HCP_PROJECT_ID=${HCP_PROJECT_ID}
      - HCP_PROJECT_NAME=${HCP_PROJECT_NAME}
    networks:
      - monk-network
    expose:
      - "8001"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/api/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - monk-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  monk-network:
    driver: bridge 