version: '3.8'

services:
  cert-gen:
    image: alpine:3.18
    command: >
      sh -c "apk add openssl &&
             openssl req -x509 -newkey rsa:4096 -keyout /certs/key.pem -out /certs/cert.pem -days 365 -nodes -subj '/CN=localhost' &&
             chmod 644 /certs/*"
    volumes:
      - certs:/certs
    restart: "no"

  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    environment:
      - BASE_URL=${BASE_URL}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - API_DOMAIN=http://backend:8001
      - INSTALL_DOMAIN=${INSTALL_DOMAIN}
      - HCP_CLIENT_ID=${HCP_CLIENT_ID}
      - HCP_CLIENT_SECRET=${HCP_CLIENT_SECRET}
      - HCP_ORG_ID=${HCP_ORG_ID}
      - HCP_PROJECT_ID=${HCP_PROJECT_ID}
      - HCP_PROJECT_NAME=${HCP_PROJECT_NAME}
    networks:
      - monk-network
    expose:
      - "8001"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/nginx/certs
    networks:
      - monk-network
    depends_on:
      - cert-gen
      - backend
      - frontend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Exposed for debugging; Nginx handles production traffic
    depends_on:
      - backend
    networks:
      - monk-network
    restart: unless-stopped

networks:
  monk-network:
    driver: bridge

volumes:
  certs: