openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /sessioninfo:
    get:
      summary: Secure Api
      operationId: secure_api_sessioninfo_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /task/:
    get:
      tags:
      - tasks
      summary: List Tasks
      operationId: list_tasks_task__get
      responses:
        '200':
          description: Get all tasks
          content:
            application/json:
              schema: {}
    post:
      tags:
      - tasks
      summary: Create Task
      operationId: create_task_task__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskModel'
        required: true
      responses:
        '200':
          description: Create a new task
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /task/{id}:
    get:
      tags:
      - tasks
      summary: Show Task
      operationId: show_task_task__id__get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      responses:
        '200':
          description: Get a single task
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - tasks
      summary: Update Task
      operationId: update_task_task__id__put
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskModel'
      responses:
        '200':
          description: Update a task
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - tasks
      summary: Delete Task
      operationId: delete_task_task__id__delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      responses:
        '200':
          description: Delete a task
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    TaskModel:
      properties:
        _id:
          type: string
          format: uuid
          title: ' Id'
        name:
          type: string
          title: Name
        goal:
          type: string
          title: Goal
        completed:
          type: boolean
          title: Completed
      type: object
      required:
      - name
      - goal
      - completed
      title: TaskModel
      example:
        completed: true
        goal: Why are we doing it?
        name: An informative task title
    UpdateTaskModel:
      properties:
        name:
          type: string
          title: Name
        goal:
          type: string
          title: Goal
        completed:
          type: boolean
          title: Completed
      type: object
      title: UpdateTaskModel
      example:
        completed: true
        goal: Why are we doing it?
        name: An informative task title
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
