name: Set env variables 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  set-api-key:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set API Key
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "API_KEY=$API_KEY" >> $GITHUB_OUTPUT

