name: Playwright Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'
  DOCKER_CACHE_DIR: /tmp/.buildx-cache
  
jobs:
  e2e-tests:
    runs-on: [self-hosted]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: ${{ env.DOCKER_CACHE_DIR }}
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Create .env file
      run: |
        cat > .env << 'EOF'
        HCP_ORG_ID=${{ secrets.HCP_ORG_ID }}
        HCP_PROJECT_ID=${{ secrets.HCP_PROJECT_ID }}
        HCP_CLIENT_ID=${{ secrets.HCP_CLIENT_ID }}
        HCP_CLIENT_SECRET=${{ secrets.HCP_CLIENT_SECRET }}
        HCP_PROJECT_NAME=${{ secrets.HCP_PROJECT_NAME }}
        BASE_URL=0.0.0.0
        FASTAPI_PORT=8001
        WEBSITE_DOMAIN=https://localhost
        INSTALL_DOMAIN=https://localhost
        API_DOMAIN=https://localhost
        
        VITE_API_DOMAIN=https://localhost
        VITE_WEBSITE_DOMAIN=https://localhost
        VITE_SUPERTOKENS_API_BASE_PATH=/api/auth
        VITE_SUPERTOKENS_WEBSITE_BASE_PATH=/auth
        VITE_SUPERTOKENS_APP_NAME=Monk
        VITE_API_BASE=/api
        TEST_GOOGLE_USERNAME=${{ secrets.TEST_GOOGLE_USERNAME }}
        TEST_GOOGLE_PASSWORD=${{ secrets.TEST_GOOGLE_PASSWORD }}
        EOF

    - name: Build backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend/api
        file: ./backend/api/Dockerfile
        tags: monk-backend:latest
        load: true
        cache-from: type=local,src=${{ env.DOCKER_CACHE_DIR }}
        cache-to: type=local,dest=${{ env.DOCKER_CACHE_DIR }},mode=max

    - name: Build tests image
      uses: docker/build-push-action@v5
      with:
        context: ./tests
        file: ./tests/Dockerfile
        tags: monk-tests:latest
        load: true
        cache-from: type=local,src=${{ env.DOCKER_CACHE_DIR }}
        cache-to: type=local,dest=${{ env.DOCKER_CACHE_DIR }},mode=max

    - name: Start core services
      run: |
        docker compose up cert-gen frontend nginx --build -d
        docker compose up backend -d
        echo "Waiting for services to initialize..."
        sleep 15  # Reduced from 60s due to healthcheck

    - name: Verify service health
      run: |
        timeout 180 bash -c 'until docker compose exec backend curl -sSf http://localhost:8001/healthcheck; do sleep 2; done'
        docker compose ps

    - name: Execute Playwright tests
      env:
        PLAYWRIGHT_VERSION: 1.51.0
      run: |
        docker compose run --rm tests pnpm test
        echo "Test exit code: $?"

    - name: Cleanup resources
      if: always()
      run: |
        docker compose down -v
        docker system prune -af
