name: Playwright Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  API_PORT: 8001
  API_DOMAIN: 0.0.0.0
  CONTAINER_NAME: monk_backend_container
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t monk_backend ./backend/api

    - name: Run Docker container
      run: |
        docker run -d \
          -p ${{ env.API_PORT }}:8001 \
          -e API_DOMAIN=http://${{ env.API_DOMAIN }}:${{ env.API_PORT }} \
          -e HCP_CLIENT_ID=${{ secrets.HCP_CLIENT_ID }} \
          -e HCP_CLIENT_SECRET=${{ secrets.HCP_CLIENT_SECRET }} \
          -e HCP_ORG_ID=${{ secrets.HCP_ORG_ID }} \
          -e HCP_PROJECT_ID=${{ secrets.HCP_PROJECT_ID }} \
          -e HCP_PROJECT_NAME=${{ secrets.HCP_PROJECT_NAME }} \
          --name ${{ env.CONTAINER_NAME }} \
          monk_backend

    - name: Add delay to ensure server is ready
      run: sleep 10

    - name: Validate container
      run: |
        echo "Using API port: ${{ env.API_PORT }}"
        echo "Accessing domain: http://${{ env.API_DOMAIN }}:${{ env.API_PORT }}"
        docker ps --filter "name=${{ env.CONTAINER_NAME }}"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: pnpm install

    #- name: Install Playwright browsers
    #  run: pnpm exec playwright install --with-deps

    - name: Debug network
      run: |
        echo "Checking network status..."
        docker logs ${{ env.CONTAINER_NAME }}
        docker inspect ${{ env.CONTAINER_NAME }}
        netstat -tulpn | grep ${{ env.API_PORT }}

    - name: check backend api is running using curl
      run: |
        # Try accessing through docker network first
        container_ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ env.CONTAINER_NAME }})
        echo "Container IP: $container_ip"
        max_attempts=5
        attempt=1
        while [ $attempt -le $max_attempts ]; do
          echo "Attempt $attempt of $max_attempts"
          response=$(curl -v -s -w "\n%{http_code}" http://${container_ip}:${{ env.API_PORT }}/docs)
          status_code=$(echo "$response" | tail -n1)
          echo "Received status code: $status_code"
          if [ "$status_code" = "200" ]; then
            echo "Backend API is running successfully"
            exit 0
          fi
          echo "Backend API check failed with status code: $status_code"
          echo "Response body:"
          echo "$response" | sed '$d'
          sleep 5
          attempt=$((attempt + 1))
        done
        echo "Backend API failed to respond after $max_attempts attempts"
        exit 1

    - name: Run Playwright tests
      working-directory: .
      env:
        API_DOMAIN: http://${{ env.API_DOMAIN }}:${{ env.API_PORT }}
      run: pnpm exec playwright test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-results
        path: playwright-report/

    - name: Cleanup
      if: always()
      run: |
        docker stop ${{ env.CONTAINER_NAME }} || true
        docker rm ${{ env.CONTAINER_NAME }} || true
